### ISSUE TITLE
Submit error when change dropdown label

### ISSUE THREAD

**Issue by sonytrinhcvn** [Unee-T-INS/frontend#20]
I just changed the label of dropdown and still keeping KEY but cannot add a new Unit, just got Lamda error.

check [this commit](https://github.com/Unee-T-INS/frontend/tree/e8b08c9a9fd451418776207f043d162c315048e5)

**Comment by sonytrinhcvn** [comment]
I've just updated the files following the guide [here](https://github.com/unee-t/frontend/search?q=Owner%2FLandlord&type=Code). But still got error, also please see lastest [commit](https://github.com/Unee-T-INS/frontend/tree/6b3f331aa9f3f4f1f6b761d022e683a9ac990253).

**Comment by franck-boullier** [comment]
# Fix Step 1 DONE:

We need to make sure that the values in the table `ut_role_types` in the BZ database are also updated:

- 'Tenant' <--> 'Account Manager(Agent, FA)'
- 'Owner/Landlord' <--> 'PolicyHolder'
- 'Contractor' <--> 'Insurer'
- 'Management Company' <--> 'My Human Resource Manager'
- 'Agent' <--> 'Others'

Fix 1 did NOT fix the issue.

# More information:

## Details from the console:
![image](https://user-images.githubusercontent.com/31331637/74599237-98be4680-50b9-11ea-9114-1ec4e29841a7.png)

## BZ Db:

### Working as expected:

- The new record for the policy is correctly inserted in the table `ut_data_to_create_units`
- The new product is created in the BZ side.
- All components are correctly created.
- All the groups we need to correctly manage permissions and accesses are created.

### Issues/unexpected stuff:

- The existing user is NOT assigned to the role in the unit. No record in the table `ut_invitation_api_data`
- We have no record for that new policy/unit in the table `ut_data_to_replace_dummy_roles`

## Mongo DB:

### Working as expected:

- The new unit/policy is created as expected:
- All default assignee are created as expected using the new category names:
![image](https://user-images.githubusercontent.com/31331637/74599406-3286f300-50bc-11ea-9bbf-89e58f86818f.png)
- We HAVE a pending invitation for the user who created that unit
![image](https://user-images.githubusercontent.com/31331637/74599445-d83a6200-50bc-11ea-89b3-c07cf5a71412.png)

### Issues/unexpected stuff:

- The existing invitation for the user in the role for the new unit/policy is NOT processed as it should be.

## Logs from Cloudwatch:

```
...
{
    "fields": {
        "app": "processinvitations",
        "commit": "1f48f08",
        "error": "sql: no rows in result set",
        "invite": {
            "_id": "kifEmBZCyhEGJXM8m",
            "caseId": 0,
            "invitedBy": 7,
            "invitee": 7,
            "isOccupant": false,
            "mefeInvitationIdIntValue": 27,
            "role": "My Account Manager",
            "type": "replace_default",
            "unitId": 30
        },
        "plugin": "relay",
        "region": "ap-southeast-1",
        "requestID": "c0648514-ecf5-469c-b0ba-90bebd1c4120",
        "stage": "production",
        "version": "29"
    },
    "level": "error",
    "timestamp": "2020-02-16T04:37:05.121056108Z",
    "message": "failed to run step1Insert"
}
{
...
```

# Learning:

The issue seems to happen when we try to assign the user to the renamed role in the newly created unit.

# To Do:

- Check the code for the Unee-T lambda API `processinvitations` to continue debugging.
- Double check the actual values we need to replace in the frontend code (this repo).

**Comment by franck-boullier** [comment]
@sonytrinhcvn what is the latest commit for a version that was working as expected (unit is created without the API error)?

**Comment by franck-boullier** [comment]
The values for the roles in the table `ut_role_types` were NOT consistent with the data in Mongo DB.

Replace the values for the roles in the table `ut_role_types` with the values we have in the Mongo DB:

- 'Tenant' <--> 'My Account Manager'
- 'Owner/Landlord' <--> 'PolicyHolder'
- 'Contractor' <--> 'My Insurer'
- 'Management Company' <--> 'My HR'
- 'Agent' <--> 'Other'

This fixed the issue .
We are now able to create a new policy

![image](https://user-images.githubusercontent.com/31331637/74599825-5ef23d80-50c3-11ea-9c9a-6968449ae895.png)
