### ISSUE TITLE
Remapping Status

### ISSUE THREAD

**Issue by sonytrinhcvn** [Unee-T-INS/frontend#25]
**IN_PROGRESS -> IN PROGRESS
STANDBY -> ON STANDBY
RESOLVED  -> RESOLVED / CLOSED
CONFIRMED -> OPEN - PENDING FOR ACTION**

**Comment by franck-boullier** [comment]
Done.

For consistency reasons I made the following changes:
IN_PROGRESS -> IN PROGRESS
STANDBY -> ON STANDBY
RESOLVED ->CLOSED - RESOLVED  (instead of `RESOLVED / CLOSED` so it's similar logic as `OPEN - PENDING ACTION`)
CONFIRMED -> OPEN - PENDING ACTION

Changes are done in the dashboard interface, logged in as administrator.
