### ISSUE TITLE
No deploy steps for DEV

### ISSUE THREAD

**Issue by tuananh1508** [Unee-T-INS/frontend#6]
Hi @kaihendry, I can not find deploy steps for DEV env, do we use Travis or CodePipeline for It?

**Comment by kaihendry** [comment]
It's the same deployment style as bugzilla-customisation.

https://github.com/Unee-T-INS/frontend/blob/master/.travis.yml calling deploy.sh

Or did I misunderstand you?

**Comment by franck-boullier** [comment]
> It's the same deployment style as bugzilla-customisation.

@kaihendry this does NOT seem to be the case: 
- in the `frontend` repo it seems that the CI is done by 
  - AWS Codebuild but ONLY when we deploy the DEV/Staging environment.
  - Travis CI when we deploy the PROD and DEMO environment.
- In the `bugzilla-customisation` repo, it seems that the CI is done by Travis CI for ALL environments (DEV/Staging, PROD and DEMO)

That's why we can't really make sense of what's what...

See https://github.com/Unee-T-INS/frontend/blob/07d06ae6a3458399cdc58a5a8e6337cfb59c5251/.travis.yml#L30

**Comment by kaihendry** [comment]
Oh sorry, IIRC I was experimenting with CodeBuild in DEV to see if it was any faster. It's not worth the fuss.

We can revert to deploying dev via Travis as with the other environs and my previous comment still holds in the sense {frontend,bugzilla-customisation} is deployed in the same way.

Same deploy.sh, where .travis.yml has the same matrix stanzas.

**Comment by franck-boullier** [comment]
OK thanks for the clarification
